### ISSUE TITLE
custom characteristic in BlueDuino 

### ISSUE THREAD

**Issue by iqbalpalemad** [AprilBrother/BlueDuino-Library#1]
hai 

i am working with this library. i would like to know can i define custom characteristics.
let me know can i use any other library to program this board.

**Comment by volca** [comment]
Sorry. You can't define custom characteristics on BlueDuino yet. Do you mean re-define the UUID for the characteristics?

**Comment by iqbalpalemad** [comment]
Now i can see two characteristic one with notify property and other with write property.
but actually i need to define  some more characteristic with custom UUID is it possible

**Comment by volca** [comment]
Not support yet for custom more characteristic

**Comment by iqbalpalemad** [comment]
i am not yet worked with BlueDuino. now i need to transmit some digital and analog sensor data to a central. So how can i do that....?  can you provide any additional examples

**Comment by volca** [comment]
You can start with the hardwareSerialMonitor sketch first. 

1. Upload the sketch to BlueDuino with Arduino IDE
2. Install app LightBlue to iPhone
3. Open app LightBlue. It will show a BLE device "ZeroBeacon", connect it and subscribe characteristic 0xFFF1, change the data type to UTF-8
4. Open serial monitor in Arduino IDE, type some string to send
5. You will see the string at app LightBlue

For transmit sensor data to your mobile, you can do this in same way. -- Just write the sensor data to Serial1's tx and you will get the data at your app.

**Comment by iqbalpalemad** [comment]
is it only possible to make use of the two available characteristics........?
can i change the UUID of these characteristics................?
what is this major and minor in the dht_logger  example..............?

**Comment by volca** [comment]
> is it only possible to make use of the two available characteristics........?

Yes

> can i change the UUID of these characteristics................?

Not support yet.

> what is this major and minor in the dht_logger example..............?

the example advertise sensor data directly. It don't need to create connection first. The data protocol is iBeacon. We use major, minor to store the sensor data. Please check the [link](http://stackoverflow.com/questions/18906988/what-is-the-ibeacon-bluetooth-profile) for more details.

**Comment by iqbalpalemad** [comment]
i have measured the current consumed by the board . which is almost 17mA . but this is too large as compared to my requirement. i need to reduce the current below 40uA to increase the battery life.
So have any solution to reduce the current consumption.............?

**Comment by volca** [comment]
How did you measure the current?

**Comment by volca** [comment]
Let's open a new issue to discuss about the power consume.

**Comment by iqbalpalemad** [comment]
please answer here [https://github.com/AprilBrother/BlueDuino-Library/issues/2](url)

**Comment by iqbalpalemad** [comment]
hai

what is the maximum value that i can transmit through major or minor.
can i transmit major as well as minor simultaneously.....................?
 in the dht logger example both data are transmitted through minor.

**Comment by volca** [comment]
The max value is 65535 (max two bytes). You can transmit major and minor in same time.

**Comment by iqbalpalemad** [comment]
i have tried a sample program which update both major and minor data at a time but which is not updated in the phone. which just update only one value either major or minor. which depends on the value first updating in the code.

this is the code i have used which updates only major value

`#include <AB_BLE.h>

AB_BLE ble(&Serial1);

#define MAJOR 100
#define MINOR 1
 
 int i=0;
void setup() {
  // put your setup code here, to run once:
 Serial.begin(9600);
    Serial1.begin(9600);
ble.println("AT+ROLE0");
    delay(100);
    ble.println("AT+RESET");
    delay(400);

    ble.println("AT+PUID06742A694C2C4359BBFE122D05B6BEEF");
    delay(100);

    ble.write("AT+MAJR");
    ble.write(MAJOR);
    delay(100);
    ble.write("AT+MINR");
    ble.write(MINOR);
    delay(100);
}

void loop() {
   int light = analogRead(A0);
   Serial.println(i);

   ble.write("AT+MAJR");
   ble.println(i);
 
if((i%30)==0){
  ble.write("AT+MINR");
   ble.println(i);
    ble.println("AT+RESET");
    delay(100);
}

 i++;
delay(1000);
}`

**Comment by iqbalpalemad** [comment]
i have tried a sample program which update both major and minor data at a time but which is not updated in the phone. which just update only one value either major or minor. which depends on the value first updating in the code.

this is the code i have used which updates only major value

```
 #include <AB_BLE.h>

AB_BLE ble(&Serial1);

#define MAJOR 100
#define MINOR 1
 
 int i=0;
void setup() {
  // put your setup code here, to run once:
 Serial.begin(9600);
    Serial1.begin(9600);
ble.println("AT+ROLE0");
    delay(100);
    ble.println("AT+RESET");
    delay(400);

    ble.println("AT+PUID06742A694C2C4359BBFE122D05B6BEEF");
    delay(100);

    ble.write("AT+MAJR");
    ble.write(MAJOR);
    delay(100);
    ble.write("AT+MINR");
    ble.write(MINOR);
    delay(100);
}

void loop() {
   int light = analogRead(A0);
   Serial.println(i);

   ble.write("AT+MAJR");
   ble.println(i);
 
if((i%30)==0){
  ble.write("AT+MINR");
   ble.println(i);
    ble.println("AT+RESET");
    delay(100);
}

 i++;
delay(1000);
}
`` `

**Comment by volca** [comment]
please add a delay(100) after these lines:

```
ble.write("AT+MAJR");
ble.println(i);
```

**Comment by iqbalpalemad** [comment]
is it necessary to add a delay. or can i update it with any other condition.because if i add a delay it will cause my final output

**Comment by volca** [comment]
You can try to reduce the delay time. But it's need for make the at command effect.

**Comment by iqbalpalemad** [comment]
how much can i reduce. is 1ms is enough

**Comment by volca** [comment]
Just try it until the command work. 100ms is a conservatism value

**Comment by iqbalpalemad** [comment]
ok let me try

**Comment by iqbalpalemad** [comment]
is it possible to transmit only integer values through major and minor.................?
can i transmit  a character or string or a character array..............?

**Comment by volca** [comment]
Major is two bytes and minor is also 2 bytes. Please check [ASCII table](https://en.wikipedia.org/wiki/ASCII). I think you can send max 4 characters in same time.

**Comment by iqbalpalemad** [comment]
ok

**Comment by iqbalpalemad** [comment]
can i get the mac address of a central when it is connected..............?

**Comment by volca** [comment]
Sorry. No such a command yet.
