### ISSUE TITLE
Power Consumption in BlueDuino...........?

### ISSUE THREAD

**Issue by iqbalpalemad** [AprilBrother/BlueDuino-Library#2]
Hai

i have applied power from a 9V battery to BlueDuino board. The board is programmed with the example chat program. i have measured the current drawn by the board which is about 17mA. which is too higher than my expectation. actually i need to reduce the power below 40uA to increase the battery life. so how can i reduce the current consumption...........?

**Comment by volca** [comment]
There's a LDO to convert 9V to 3.3V. 9 - 3.3 = 5.7V. It drain much current. Please try to replace with a lipo battery (3.7V~).

**Comment by iqbalpalemad** [comment]
can i disconnect the onboard LED.............?

**Comment by volca** [comment]
yes. you can remove the LED for power saving

**Comment by iqbalpalemad** [comment]
how can i remove that..............?
how much current is required to the led.....?

**Comment by volca** [comment]
You need a soldering to remove the LED. I think the current is about 10mA

**Comment by iqbalpalemad** [comment]
i need to reduce the power below 40uA. what can i do for that.

**Comment by volca** [comment]
There're two micro controller in BlueDuino - ATMega32U4 and CC2540 BLE module. 

For BLE module, no sleep feature at current firmware. We may add an AT command for sleep.

For 32u4, do you find out something at google?

**Comment by iqbalpalemad** [comment]
can i close the uart to stop communication with serial monitor

**Comment by iqbalpalemad** [comment]
in nrf blue tooth chips i was able to close the uart. which will disable the communication with the serial monitor. so by that i was able to reduce the current blem 100uA. so can i do such any thing in BlueDuino to reduce the power consumption

**Comment by volca** [comment]
Sorry. You can't do that with this chip. We will add a new command ```AT+SLEEP``` in next firmware

**Comment by volca** [comment]
see this [link](http://bbs.aprbrother.com/t/allow-connection-based-on-mac-address/845/3?u=aprilpea). New firmware has a command to make BLE module go to sleep.
