### ISSUE TITLE
USB is closed accidently...........!

### ISSUE THREAD

**Issue by iqbalpalemad** [AprilBrother/BlueDuino-Library#3]
Hai

i am using a BlueDuino in my project. in my project i have to reduce the power consumption as much as low. for that i have just tested an example program from the following library 
 
[https://github.com/rocketscream/Low-Power/blob/master/Examples/idleWakePeriodic/idleWakePeriodic.ino](url)

in these example i have these line of code which will turn off the corresponding functionalities of board. 

`LowPower.idle(SLEEP_8S, ADC_OFF, TIMER4_OFF, TIMER3_OFF, TIMER1_OFF, 
  		  TIMER0_OFF, SPI_OFF, USART1_OFF, TWI_OFF, USB_OFF);`

So i think now the usb functionality of my board is closed.Now my pc is not detecting my board . and i cant even upload any sketch. i need to stop execution of the program and come back to previous state. 
so how can i reset the board..................?
can i stop execution of the current program....................?

**Comment by iqbalpalemad** [comment]
Hai

the problem is solved 

thank you

**Comment by volca** [comment]
Please see [the wiki](http://wiki.aprbrother.com/wiki/BlueDuino_Rev2_Troubleshooting_and_FAQ#How_to_Revive_a_.E2.80.9CBricked.E2.80.9D_BlueDuino_Rev2) to revive the board
