### ISSUE TITLE
How to identify a peripheral when scaning...............?

### ISSUE THREAD

**Issue by iqbalpalemad** [AprilBrother/BlueDuino-Library#4]
hai 

when my BlueDuino is working under role 1 . when i am scan using AT+SCAN2 i got only the mac address and rssi. but i am transmitting some data too the data is not found by the board.
 and i need to identify each peripheral trying to connect to the board.......?
how can i solve these issues.

![screenshot 43](https://cloud.githubusercontent.com/assets/22958585/21339405/f82f4378-c6a4-11e6-8749-14ee5aa87a49.png)

this is the output

**Comment by volca** [comment]
see #6
