### ISSUE TITLE
identify and seperate data...............?

### ISSUE THREAD

**Issue by iqbalpalemad** [AprilBrother/BlueDuino-Library#5]
Hai 

i have set my BlueDuino in role 2 to scan some beacons. now  i got a long data like this

OK+SCAN:4201A2D65AF2,8CB3503700784E18B9F05CC8B829CA4F,10,11,-65,-51 

i understand that which is a combination of MAC,UUID,MAJOR,MINOR,POWER and RSSI

now i need to separate each of them and assign it into some variable.
because i need to do some operations according major and minor as well as with MAC and RSSI

**Comment by volca** [comment]
Please check the [topic](http://arduino.stackexchange.com/questions/1013/how-do-i-split-an-incoming-string) for how to spilit a string
