### ISSUE TITLE
how to disconnect a central device...........?

### ISSUE THREAD

**Issue by iqbalpalemad** [AprilBrother/BlueDuino-Library#6]
in order to provide security i need to allow connection to my trusted devices only.so if BlueDuino identify that the connected device is not trusted then it should disconnect that central.
so for that which AT command should i use.............?

**Comment by volca** [comment]
Please discuss at [our support forum](http://bbs.aprbrother.com/c/arduino) instead. Don't make duplicate topic at these places.
